version: "3.9"

services:
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3.1
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  rsyslog:
    container_name: rsyslog
    image: rsyslog_custom
    build:
        context: .
    ports:
      - "1514:514/udp"
      - "1514:514/tcp"
    volumes:
      - ${PWD}/etc/rsyslog.conf:/etc/rsyslog.conf
      - ${PWD}/etc/rsyslog.d:/etc/rsyslog.d
    depends_on:
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
